---
# Copyright 2016, AT&T, ASTRA, and it's Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: build /etc/hosts
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_default_ipv4.address }} {{item}} {{item}}.{{osa_domain}}" state=present
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: groups['all']

- name: make sure that correct repositories are loaded
  template: src=sources.list.j2 dest=/etc/apt/sources.list backup=yes owner=root group=root mode="u=rw,g=r,o=r"
  when: ansible_distribution == 'Ubuntu'

- name: add prerequisites for the deploy-host
  apt: name={{ item }} update_cache=yes state=present state=latest
  with_items:
    - ntp
    - ntpdate
    - openssh-server
    - sudo

- name: set timezone to America/New_York
  raw: echo "America/New_York" | sudo tee /etc/timezone

- name: commit the timezone changes
  raw: dpkg-reconfigure --frontend noninteractive tzdata
  notify:
    - restart ntp
