---
# Copyright 2016, AT&T, ASTRA, and it's Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# All Hosts: Prerequisite Tasks
- hosts: all
  gather_facts: true
  sudo: yes
  roles:
    - deploy-prep
  tags:
    - deploy-prep

# Deployment Hosts
- hosts: deploy-host
  sudo: yes
  roles:
    - deploy-host
#    - deploy-ceph
  tags:
    - deploy-host

# Target Hosts
- hosts: target-host
  sudo: yes
  roles:
    - target-host
  tags:
    - target-host

# Docker Hosts
#- hosts: docker-host
#  sudo: yes
#  roles:
#    - { role: deploy-docker, when: "docker_hosts == 'true'" }
#  ignore_errors: yes

# Ceph Monitor Hosts
- hosts: ceph-mon
  sudo: yes
  roles:
    - ceph-mon
#    - { role: ceph-restapi, when: restapi_group_name is defined and restapi_group_name in group_names }
#  serial: 1

# Ceph Agents
- hosts: agents
  become: True
  roles:
  - ceph-agent

# Ceph OSD Hosts
- hosts: ceph-osd
  sudo: yes
  roles:
    - ceph-osd

# Ceph MDS Hosts
#- hosts: ceph-mds
#  sudo: yes
#  roles:
#    - ceph-mds

# Ceph RGW Hosts
#- hosts: ceph-rgw
#  sudo: yes
#  roles:
#    - ceph-rgw

# Ceph REST-API Hosts
#- hosts: restapis
#  become: True
#  roles:
#  - ceph-restapi
